# Плейлисты
## Получить список треков
GET http://localhost:8000/api/v1/tracks HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzJiM2NiYmIwNjhiMmYwY2U5NWYwNTAiLCJpYXQiOjE3MzEyMzE1NTksImV4cCI6MTczMTQwNDM1OX0.ggaJDixflYV3PK-Bu9d2xzA-vdEmbn1LVqVyyG-YlII

###

## Загрузка из папки новых треков 
GET http://localhost:8000/api/v1/tracks/load HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzJiM2NiYmIwNjhiMmYwY2U5NWYwNTAiLCJpYXQiOjE3MzEyNDA3NzIsImV4cCI6MTczMTQxMzU3Mn0.cZ3FP1hyx7x3ggYtAIHyl5FcCmgQeH9WDP9GPjG0dCo

###

## Редактирование трека
PATCH http://localhost:8000/api/v1/tracks HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

{
  "id": "79597552-cd15-4ab8-9611-2e90063b396c",
  "folderId": "123"
}

###

## Удаление трека
DELETE http://localhost:8000/api/v1/tracks/79597552-cd15-4ab8-9611-2e90063b396c HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NzI4NzljNmFmY2JmYWY4YjdjNDEzYWIiLCJpYXQiOjE3MzA3OTg2MTAsImV4cCI6MTczMDk3MTQxMH0.ovcfrRHJMTt1np5lff3G5TziAGkzrp0BIZaH2_Jtbug

###