export const TYPES = {
	Application: Symbol.for('Application'),
	Logger: Symbol.for('Logger'),
	TrackController: Symbol.for('TrackController'),
	TrackService: Symbol.for('TrackService'),
	PlaylistController: Symbol.for('PlaylistController'),
	PlaylistService: Symbol.for('PlaylistService'),
	PlaylistRepository: Symbol.for('PlaylistRepository'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	TrackRepository: Symbol.for('TrackRepository'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	UserRepository: Symbol.for('UserRepository'),
};
